// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: lessons/29-capstone-final/exercises/proto/logstats.proto

package logstatspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescGZIP(), []int{0}
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type IngestSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Parsed        int32                  `protobuf:"varint,2,opt,name=parsed,proto3" json:"parsed,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSummary) Reset() {
	*x = IngestSummary{}
	mi := &file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSummary) ProtoMessage() {}

func (x *IngestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSummary.ProtoReflect.Descriptor instead.
func (*IngestSummary) Descriptor() ([]byte, []int) {
	return file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescGZIP(), []int{1}
}

func (x *IngestSummary) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestSummary) GetParsed() int32 {
	if x != nil {
		return x.Parsed
	}
	return 0
}

func (x *IngestSummary) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescGZIP(), []int{2}
}

type StatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        map[string]int32       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsReply) Reset() {
	*x = StatsReply{}
	mi := &file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReply) ProtoMessage() {}

func (x *StatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReply.ProtoReflect.Descriptor instead.
func (*StatsReply) Descriptor() ([]byte, []int) {
	return file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescGZIP(), []int{3}
}

func (x *StatsReply) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *StatsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_lessons_29_capstone_final_exercises_proto_logstats_proto protoreflect.FileDescriptor

const file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDesc = "" +
	"\n" +
	"8lessons/29-capstone-final/exercises/proto/logstats.proto\x12\vlogstats.v1\"\x1d\n" +
	"\aLogLine\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"[\n" +
	"\rIngestSummary\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x16\n" +
	"\x06parsed\x18\x02 \x01(\x05R\x06parsed\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\"\x0e\n" +
	"\fStatsRequest\"\x9a\x01\n" +
	"\n" +
	"StatsReply\x12;\n" +
	"\x06counts\x18\x01 \x03(\v2#.logstats.v1.StatsReply.CountsEntryR\x06counts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\x88\x01\n" +
	"\bLogStats\x12<\n" +
	"\x06Ingest\x12\x14.logstats.v1.LogLine\x1a\x1a.logstats.v1.IngestSummary(\x01\x12>\n" +
	"\bGetStats\x12\x19.logstats.v1.StatsRequest\x1a\x17.logstats.v1.StatsReplyBZZXgithub.com/ristkari-dev/go-training/lessons/29-capstone-final/exercises/proto/logstatspbb\x06proto3"

var (
	file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescOnce sync.Once
	file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescData []byte
)

func file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescGZIP() []byte {
	file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescOnce.Do(func() {
		file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDesc), len(file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDesc)))
	})
	return file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDescData
}

var file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_lessons_29_capstone_final_exercises_proto_logstats_proto_goTypes = []any{
	(*LogLine)(nil),       // 0: logstats.v1.LogLine
	(*IngestSummary)(nil), // 1: logstats.v1.IngestSummary
	(*StatsRequest)(nil),  // 2: logstats.v1.StatsRequest
	(*StatsReply)(nil),    // 3: logstats.v1.StatsReply
	nil,                   // 4: logstats.v1.StatsReply.CountsEntry
}
var file_lessons_29_capstone_final_exercises_proto_logstats_proto_depIdxs = []int32{
	4, // 0: logstats.v1.StatsReply.counts:type_name -> logstats.v1.StatsReply.CountsEntry
	0, // 1: logstats.v1.LogStats.Ingest:input_type -> logstats.v1.LogLine
	2, // 2: logstats.v1.LogStats.GetStats:input_type -> logstats.v1.StatsRequest
	1, // 3: logstats.v1.LogStats.Ingest:output_type -> logstats.v1.IngestSummary
	3, // 4: logstats.v1.LogStats.GetStats:output_type -> logstats.v1.StatsReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lessons_29_capstone_final_exercises_proto_logstats_proto_init() }
func file_lessons_29_capstone_final_exercises_proto_logstats_proto_init() {
	if File_lessons_29_capstone_final_exercises_proto_logstats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDesc), len(file_lessons_29_capstone_final_exercises_proto_logstats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lessons_29_capstone_final_exercises_proto_logstats_proto_goTypes,
		DependencyIndexes: file_lessons_29_capstone_final_exercises_proto_logstats_proto_depIdxs,
		MessageInfos:      file_lessons_29_capstone_final_exercises_proto_logstats_proto_msgTypes,
	}.Build()
	File_lessons_29_capstone_final_exercises_proto_logstats_proto = out.File
	file_lessons_29_capstone_final_exercises_proto_logstats_proto_goTypes = nil
	file_lessons_29_capstone_final_exercises_proto_logstats_proto_depIdxs = nil
}
