// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: lessons/25-grpc/exercises/proto/logstats.proto

package logstatspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogStats_Ingest_FullMethodName   = "/logstats.v1.LogStats/Ingest"
	LogStats_GetStats_FullMethodName = "/logstats.v1.LogStats/GetStats"
)

// LogStatsClient is the client API for LogStats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LogStats accepts log lines and reports per-level counts. It mirrors
// the HTTP service's /ingest and /stats over a typed, streaming RPC API.
type LogStatsClient interface {
	// Ingest streams many log lines and returns one summary (client-streaming).
	Ingest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogLine, IngestSummary], error)
	// GetStats returns the accumulated per-level counts (unary).
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsReply, error)
}

type logStatsClient struct {
	cc grpc.ClientConnInterface
}

func NewLogStatsClient(cc grpc.ClientConnInterface) LogStatsClient {
	return &logStatsClient{cc}
}

func (c *logStatsClient) Ingest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogLine, IngestSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogStats_ServiceDesc.Streams[0], LogStats_Ingest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogLine, IngestSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStats_IngestClient = grpc.ClientStreamingClient[LogLine, IngestSummary]

func (c *logStatsClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsReply)
	err := c.cc.Invoke(ctx, LogStats_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogStatsServer is the server API for LogStats service.
// All implementations must embed UnimplementedLogStatsServer
// for forward compatibility.
//
// LogStats accepts log lines and reports per-level counts. It mirrors
// the HTTP service's /ingest and /stats over a typed, streaming RPC API.
type LogStatsServer interface {
	// Ingest streams many log lines and returns one summary (client-streaming).
	Ingest(grpc.ClientStreamingServer[LogLine, IngestSummary]) error
	// GetStats returns the accumulated per-level counts (unary).
	GetStats(context.Context, *StatsRequest) (*StatsReply, error)
	mustEmbedUnimplementedLogStatsServer()
}

// UnimplementedLogStatsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogStatsServer struct{}

func (UnimplementedLogStatsServer) Ingest(grpc.ClientStreamingServer[LogLine, IngestSummary]) error {
	return status.Errorf(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedLogStatsServer) GetStats(context.Context, *StatsRequest) (*StatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedLogStatsServer) mustEmbedUnimplementedLogStatsServer() {}
func (UnimplementedLogStatsServer) testEmbeddedByValue()                  {}

// UnsafeLogStatsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogStatsServer will
// result in compilation errors.
type UnsafeLogStatsServer interface {
	mustEmbedUnimplementedLogStatsServer()
}

func RegisterLogStatsServer(s grpc.ServiceRegistrar, srv LogStatsServer) {
	// If the following call pancis, it indicates UnimplementedLogStatsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogStats_ServiceDesc, srv)
}

func _LogStats_Ingest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogStatsServer).Ingest(&grpc.GenericServerStream[LogLine, IngestSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStats_IngestServer = grpc.ClientStreamingServer[LogLine, IngestSummary]

func _LogStats_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogStatsServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogStats_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogStatsServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogStats_ServiceDesc is the grpc.ServiceDesc for LogStats service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogStats_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logstats.v1.LogStats",
	HandlerType: (*LogStatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _LogStats_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ingest",
			Handler:       _LogStats_Ingest_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "lessons/25-grpc/exercises/proto/logstats.proto",
}
